#!/bin/sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -o remount,rw /
/bin/busybox mount -a
/bin/busybox --install -s

mount -t devtmpfs devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

for i in /etc/init.d/S??*
do
	$i start
done

ifup eth0
